-- 04_sync_schema.sql
-- Self-contained migration. Run this in your Supabase SQL Editor.
-- It creates any missing tables (employers, employer_members) and
-- patches jobs + applications with the FK columns and RLS needed
-- for the secure employer-candidate sync architecture.
-- Also adds lat, lng, duration, start_date, work_model to jobs if missing.

-- ── 0. Prerequisite helper function (idempotent) ──────────────────────────────
-- This is used by RLS policies. Safe to re-run.
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS TEXT LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT role::text FROM public.user_roles WHERE user_id = auth.uid() LIMIT 1;
$$;

-- ── 1. Create employers table (if not already created by 02_auth_roles_schema) ─
CREATE TABLE IF NOT EXISTS public.employers (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL,
  website     TEXT,
  logo_url    TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.employers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Employers can read own record" ON public.employers;
CREATE POLICY "Employers can read own record"
  ON public.employers FOR SELECT
  USING (
    id IN (SELECT employer_id FROM public.employer_members WHERE user_id = auth.uid())
  );

-- ── 2. Create employer_members table (if not already created) ─────────────────
CREATE TABLE IF NOT EXISTS public.employer_members (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  employer_id UUID NOT NULL REFERENCES public.employers(id) ON DELETE CASCADE,
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role        TEXT NOT NULL DEFAULT 'admin',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (employer_id, user_id)
);

ALTER TABLE public.employer_members ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Members can read own memberships" ON public.employer_members;
CREATE POLICY "Members can read own memberships"
  ON public.employer_members FOR SELECT
  USING (user_id = auth.uid());

-- ── 3. Patch the jobs table ───────────────────────────────────────────────────
ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS employer_id  UUID REFERENCES public.employers(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS lat          DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS lng          DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS duration     TEXT,
  ADD COLUMN IF NOT EXISTS start_date   TEXT,
  ADD COLUMN IF NOT EXISTS work_model   TEXT;

CREATE INDEX IF NOT EXISTS idx_jobs_employer_id ON public.jobs(employer_id);

-- Drop the old open-write policy and replace with role-gated ones
DROP POLICY IF EXISTS "Allow public insert jobs" ON public.jobs;
DROP POLICY IF EXISTS "Allow public read jobs"   ON public.jobs;
DROP POLICY IF EXISTS "Anyone can read jobs"       ON public.jobs;
DROP POLICY IF EXISTS "Employers can insert own jobs" ON public.jobs;
DROP POLICY IF EXISTS "Employers can update own jobs" ON public.jobs;
DROP POLICY IF EXISTS "Employers can delete own jobs" ON public.jobs;

CREATE POLICY "Anyone can read jobs"
  ON public.jobs FOR SELECT USING (true);

CREATE POLICY "Employers can insert own jobs"
  ON public.jobs FOR INSERT
  WITH CHECK (
    get_user_role() = 'employer' AND
    employer_id IN (
      SELECT employer_id FROM public.employer_members WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Employers can update own jobs"
  ON public.jobs FOR UPDATE
  USING (
    get_user_role() = 'employer' AND
    employer_id IN (
      SELECT employer_id FROM public.employer_members WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Employers can delete own jobs"
  ON public.jobs FOR DELETE
  USING (
    get_user_role() = 'employer' AND
    employer_id IN (
      SELECT employer_id FROM public.employer_members WHERE user_id = auth.uid()
    )
  );

-- ── 4. Create applications table (if missing) + patch with FK columns ─────────
CREATE TABLE IF NOT EXISTS public.applications (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id          BIGINT REFERENCES public.jobs(id) ON DELETE CASCADE,
  student_name    TEXT,
  student_email   TEXT,
  student_profile JSONB,
  ai_score        INTEGER,
  ai_reasoning    TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.applications
  ADD COLUMN IF NOT EXISTS candidate_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS employer_id  UUID REFERENCES public.employers(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_applications_candidate_id ON public.applications(candidate_id);
CREATE INDEX IF NOT EXISTS idx_applications_employer_id  ON public.applications(employer_id);

ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Candidates read own applications"   ON public.applications;
DROP POLICY IF EXISTS "Candidates insert own applications" ON public.applications;
DROP POLICY IF EXISTS "Employers read company applications" ON public.applications;

-- Candidates see only their own
CREATE POLICY "Candidates read own applications"
  ON public.applications FOR SELECT
  USING (auth.uid() = candidate_id);

-- Candidates insert only for themselves
CREATE POLICY "Candidates insert own applications"
  ON public.applications FOR INSERT
  WITH CHECK (
    get_user_role() = 'candidate' AND
    auth.uid() = candidate_id
  );

-- Employers see all applications for their company
CREATE POLICY "Employers read company applications"
  ON public.applications FOR SELECT
  USING (
    get_user_role() = 'employer' AND
    employer_id IN (
      SELECT employer_id FROM public.employer_members WHERE user_id = auth.uid()
    )
  );
