-- ══════════════════════════════════════════════════════════════════════════════
-- ██████████████████████████████████████████████████████████████████████████████
-- ██                                                                        ██
-- ██  ⚠️  CRITICAL — DO NOT DROP THE "submissions" TABLE                    ██
-- ██                                                                        ██
-- ██  This table stores ALL landing page signups (email + phone).            ██
-- ██  It is the CORE of user acquisition for unemployed.sk.                 ██
-- ██  DO NOT drop, truncate, or remove RLS policies from this table.        ██
-- ██  Any schema changes must be ADDITIVE (ALTER TABLE ADD COLUMN).         ██
-- ██                                                                        ██
-- ██████████████████████████████████████████████████████████████████████████████
-- ══════════════════════════════════════════════════════════════════════════════

-- Ensure the submissions table exists with all required columns
CREATE TABLE IF NOT EXISTS public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    phone_prefix TEXT,
    phone TEXT,
    user_type TEXT NOT NULL,
    consented BOOLEAN DEFAULT TRUE,
    marketing_consent BOOLEAN DEFAULT FALSE,
    ip_hash TEXT,
    company_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

-- ══════════════════════════════════════════════════════════════════════════════
-- RLS POLICIES FOR SUBMISSIONS TABLE
-- The server uses the SERVICE ROLE KEY which bypasses RLS entirely.
-- These policies exist as a safety net for any anon-key access.
-- ══════════════════════════════════════════════════════════════════════════════

-- Allow inserts from the landing page signup form
DROP POLICY IF EXISTS "Allow public insert submissions" ON public.submissions;
CREATE POLICY "Allow public insert submissions"
  ON public.submissions
  FOR INSERT
  WITH CHECK (true);

-- Allow service-role reads for duplicate checking
-- (The service role key bypasses RLS, but this is here as documentation)
DROP POLICY IF EXISTS "Allow service select submissions" ON public.submissions;
CREATE POLICY "Allow service select submissions"
  ON public.submissions
  FOR SELECT
  USING (true);
