-- UNEMPLOYED.SK - SUPABASE DATABASE SETUP
-- PASTE THIS INTO THE SUPABASE SQL EDITOR AND RUN

-- 1. Create Submissions Table (Registrations)
CREATE TABLE IF NOT EXISTS public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    phone_prefix TEXT,
    phone TEXT,
    user_type TEXT NOT NULL,
    consented BOOLEAN DEFAULT TRUE,
    marketing_consent BOOLEAN DEFAULT FALSE,
    ip_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Jobs Table
CREATE TABLE IF NOT EXISTS public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    logo TEXT,
    color TEXT DEFAULT '#FF5C00',
    location TEXT,
    rate TEXT,
    rate_unit TEXT,
    hours TEXT,
    type TEXT,
    tags JSONB DEFAULT '[]'::jsonb,
    schedule TEXT,
    match_score INTEGER DEFAULT 95,
    reason TEXT,
    description TEXT,
    requirements TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable RLS (Row Level Security) - Basic Setup
-- For now, we allow reading and writing for development
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read jobs" ON public.jobs FOR SELECT USING (true);
CREATE POLICY "Allow public insert jobs" ON public.jobs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public insert submissions" ON public.submissions FOR INSERT WITH CHECK (true);
